### ISSUE TITLE
Understanding ENV file

### ISSUE THREAD

**Issue by guilloutran** [Prem-ium/BingRewards#32]
Hi,

I'm trying to get mine version of the script working but I couldn't figure out what would I need to put in the URL in the env file.

**Comment by Prem-ium** [comment]
Hey Nghia Tran,

If you open up the Bing homepage in incognito mode and click the "Sign In" button. The button should take you to the login page, where you can copy the URL and assign it to the URL env variable. It should be a long URL starting with login.live.

EX: https://login.live.com/login.srf?{QUERY}

**Comment by badplay** [comment]
should i do this for all profiles ????

alsow what is punchcard ?? i used and tested other bots they alsow have punchcard but there is no trrue false  option so  i dont know what  this is. are punch card this this or that quiz??

i use german CET time zone for keep  alive but it cant float to flask i want to use 8:03 in the morning

**Comment by badplay** [comment]
and i  get this error
Traceback (most recent call last):
  File "main.py", line 1106, in start_rewards
    ranRewards, totalPointsReport, totalDifference, differenceReport = run_rewards(EMAIL, PASSWORD, ranRewards, totalPointsReport, totalDifference, differenceReport)
  File "main.py", line 1039, in run_rewards
    driver = get_driver()
  File "main.py", line 245, in get_driver
    options.add_argument('--no-sandbox')
UnboundLocalError: local variable 'options' referenced before assignment

**Comment by Prem-ium** [comment]
Hello @badplay,

As the original issue has been resolved, I am closing this issue guilloutran has created. If you continue having issues, open up a separate issue.
