### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by Juice805** [Prem-ium/BingRewards#36]
With `.env`:
```
URL=https://login.live.com/login.srf?{QUERY}
HEADLESS=True
MULTITHREADING=True
AUTO_REDEEM=False
TZ=America/Los_Angeles
TIMER=False
BROWSER=chrome
```

Running the Docker image `nelsondane/bing-rewards` (Digest: `ec38f40ef64d661bfc5d85cc88799928404acc94821512c4e22ebe07a0931ecb`) with:
```
docker run -it --rm --env-file ./.env --name bing-rewards nelsondane/bing-rewards
```

Outputs:
```
rm: cannot remove '/tmp/.X99-lock': No such file or directory
Starting X virtual framebuffer (Xvfb) in background...
BROWSER: chrome
HANDLE_DRIVER: False
Starting Bing Rewards Bot...
Multithreading is enabled in .env.
This will allow you to run multiple accounts at once, but it may also increase the chance of being banned and leads to more CPU usage.
Use at your own risk.
Current IPv4 Address: X.X.X.X
Unable to get IPv6 address


Starting Bing Rewards Automation:	2022-12-20 22:35:09.563978-08:00

Exception in thread Thread-1 (run_rewards):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/app/main.py", line 1182, in run_rewards
    driver = get_driver()
  File "/app/main.py", line 260, in get_driver
    driver = webdriver.Chrome(options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 106, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x00400066a2a3 <unknown>
#1 0x004000428f77 <unknown>
#2 0x0040004515f7 <unknown>
#3 0x00400044d7d0 <unknown>
#4 0x00400048e0b7 <unknown>
#5 0x00400048da5f <unknown>
#6 0x004000485903 <unknown>
#7 0x004000458ece <unknown>
#8 0x004000459fde <unknown>
#9 0x0040006ba63e <unknown>
#10 0x0040006bdb79 <unknown>
#11 0x0040006a089e <unknown>
#12 0x0040006bea83 <unknown>
#13 0x004000693505 <unknown>
#14 0x0040006dfca8 <unknown>
#15 0x0040006dfe36 <unknown>
#16 0x0040006fb333 <unknown>
#17 0x004002ad6b43 <unknown>

Bing Rewards Automation Complete!
2022-12-20 22:35:15.401242-08:00
Sleeping for 5 hours before rechecking...
```
Found [this SO issue](https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t), but I see that the arg is used, so I'm unsure how to fix.

**Comment by Prem-ium** [comment]
Some things to try:
- Set the HANDLE_DRIVER variable to True
- Remove or set the 'HEADLESS' variable to False.


For some reason HANDLE_DRIVER isn't being set to True by default, it is running a method reliant on a driver being present in the directory.

**Comment by Juice805** [comment]
Unfortunately it has the same error with both changes.

**Comment by Juice805** [comment]
Looks like it may be due to the machine architecture. On an AMD64 machine it is working, but on ARM64 it hits the above error.

Could the publisher for the [docker image](https://hub.docker.com/r/nelsondane/bing-rewards) be updated to use `buildx` and create ARM64 images?

**Comment by NelsonDane** [comment]
Hello @Juice805 , thanks for your interest in the bot! We've done some testing with `buildx` and the bot on ARM64 but haven't been able to get anything to work. Furthermore, neither @Prem-ium or I have a ARM64 device to test the bot with, and so at this time ARM64 isn't supported. Unfortunately just adding the ARM64 tag with `buildx` didn't solve any problems.

**Comment by Juice805** [comment]
This isn't fixed, but looks like it may be a bug in ChromeDriver:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2473
