### ISSUE TITLE
Trouble getting back to searches after URL's and quizzes.

### ISSUE THREAD

**Issue by gempath** [Prem-ium/BingRewards#41]
Love the bot.  Playing around with it now.  After finishing URL's and quizzes I got this:

Attempting to restart Mobile search in 500 seconds
[19836:18892:0116/220111.637:ERROR:device_event_log_impl.cc(215)] [22:01:11.639] USB: usb_device_handle_win.cc:1045 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[19836:20940:0116/220209.550:ERROR:util.cc(133)] Can't create base directory: C:\Program Files\Google\GoogleUpdater
[19108:19392:0116/220309.610:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

DevTools listening on ws://127.0.0.1:50999/devtools/browser/5f549edf-54c6-4b87-ad5c-454d211d0f99
[15628:18064:0116/220941.194:ERROR:device_event_log_impl.cc(215)] [22:09:41.194] USB: usb_device_handle_win.cc:1045 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1114, in mobile_helper
    mobile_search(driver, EMAIL, PASSWORD, MOBILE_SEARCHES)
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1070, in mobile_search
    driver.get(os.environ['URL'])
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=108.0.5359.126)
Stacktrace:
Backtrace:
        (No symbol) [0x0048F243]
        (No symbol) [0x00417FD1]
        (No symbol) [0x0030CF10]
        (No symbol) [0x003000EE]
        (No symbol) [0x002FEA07]
        (No symbol) [0x002FEDC2]
        (No symbol) [0x0030EA5B]
        (No symbol) [0x0036D187]
        (No symbol) [0x0035858C]
        (No symbol) [0x0036C9EB]
        (No symbol) [0x00358386]
        (No symbol) [0x0033163C]
        (No symbol) [0x0033269D]
        GetHandleVerifier [0x00729A22+2655074]
        GetHandleVerifier [0x0071CA24+2601828]
        GetHandleVerifier [0x00538C0A+619850]
        GetHandleVerifier [0x00537830+614768]
        (No symbol) [0x004205FC]
        (No symbol) [0x00425968]
        (No symbol) [0x00425A55]
        (No symbol) [0x0043051B]
        BaseThreadInitThunk [0x768B00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77DF7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77DF7B8E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1145, in update_searches
    PC = driver.find_element(By.XPATH, value='//*[@id="userPointsBreakdown"]/div/div[2]/div/div[1]/div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[2]').text.replace(" ", "").split("/")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 861, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="userPointsBreakdown"]/div/div[2]/div/div[1]/div/div[2]/mee-rewards-user-points-details/div/div/div/div/p[2]"}
  (Session info: chrome=108.0.5359.126)
Stacktrace:
Backtrace:
        (No symbol) [0x0048F243]
        (No symbol) [0x00417FD1]
        (No symbol) [0x0030D04D]
        (No symbol) [0x0033C0B0]
        (No symbol) [0x0033C22B]
        (No symbol) [0x0036E612]
        (No symbol) [0x003585D4]
        (No symbol) [0x0036C9EB]
        (No symbol) [0x00358386]
        (No symbol) [0x0033163C]
        (No symbol) [0x0033269D]
        GetHandleVerifier [0x00729A22+2655074]
        GetHandleVerifier [0x0071CA24+2601828]
        GetHandleVerifier [0x00538C0A+619850]
        GetHandleVerifier [0x00537830+614768]
        (No symbol) [0x004205FC]
        (No symbol) [0x00425968]
        (No symbol) [0x00425A55]
        (No symbol) [0x0043051B]
        BaseThreadInitThunk [0x768B00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77DF7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77DF7B8E+238]

Exception: get_driver() got an unexpected keyword argument 'mobile'

Traceback (most recent call last):
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1114, in mobile_helper
    mobile_search(driver, EMAIL, PASSWORD, MOBILE_SEARCHES)
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1070, in mobile_search
    driver.get(os.environ['URL'])
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 455, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\INSPIRON 3670\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument
  (Session info: chrome=108.0.5359.126)
Stacktrace:
Backtrace:
        (No symbol) [0x0048F243]
        (No symbol) [0x00417FD1]
        (No symbol) [0x0030CF10]
        (No symbol) [0x003000EE]
        (No symbol) [0x002FEA07]
        (No symbol) [0x002FEDC2]
        (No symbol) [0x0030EA5B]
        (No symbol) [0x0036D187]
        (No symbol) [0x0035858C]
        (No symbol) [0x0036C9EB]
        (No symbol) [0x00358386]
        (No symbol) [0x0033163C]
        (No symbol) [0x0033269D]
        GetHandleVerifier [0x00729A22+2655074]
        GetHandleVerifier [0x0071CA24+2601828]
        GetHandleVerifier [0x00538C0A+619850]
        GetHandleVerifier [0x00537830+614768]
        (No symbol) [0x004205FC]
        (No symbol) [0x00425968]
        (No symbol) [0x00425A55]
        (No symbol) [0x0043051B]
        BaseThreadInitThunk [0x768B00F9+25]
        RtlGetAppContainerNamedObjectPath [0x77DF7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77DF7B8E+238]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1340, in main
    start_rewards()
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1286, in start_rewards
    mobile_helper(EMAIL, PASSWORD, MOBILE_SEARCHES)
  File "C:\Users\INSPIRON 3670\Desktop\BingRewards-main\main.py", line 1128, in mobile_helper
    driver = get_driver(mobile=True)
             ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_driver() got an unexpected keyword argument 'mobile'

 Attempting to restart Bing Rewards Automation in 10 minutes...

**Comment by Prem-ium** [comment]
This issue should be fixed in the latest commit. Thank you.
