### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError

### ISSUE THREAD

**Issue by lostliam** [Prem-ium/BingRewards#53]
Hello! Thanks for your working! Sorry to bother you about the docker version problem.
Environment: Win10   Docker Desktop
Problem: Rasie the TimeZoneError , Changed the .env but it still doesn't work
Log:
First TIME:

  rm: cannot remove '/tmp/.X99-lock': No such file or directory
Starting X virtual framebuffer (Xvfb) in background...
BROWSER: 'chrome'
HANDLE_DRIVER: True
Starting Bing Rewards Bot...
Traceback (most recent call last):
  File "/app/main.py", line 135, in <module>
    TZ = timezone(os.environ.get("TZ", "America/New_York"))
  File "/usr/local/lib/python3.10/dist-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: "'America/New_York'"

I changed the .env   trying to keep it same as my windows os.
Still Raise:

rm: cannot remove '/tmp/.X99-lock': No such file or directory
Starting X virtual framebuffer (Xvfb) in background...
BROWSER: 'chrome'
HANDLE_DRIVER: True
Starting Bing Rewards Bot...
Traceback (most recent call last):
  File "/app/main.py", line 135, in <module>
    TZ = timezone(os.environ.get("TZ", "America/New_York"))
  File "/usr/local/lib/python3.10/dist-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: "'Asia/Shanghai'"

Could you help me and thank you very much!

**Comment by lostliam** [comment]
Deleting the single quotation marks in the .env file seems to solve this problem.
Hope can help others.
