### ISSUE TITLE
Unable to start Docker Container

### ISSUE THREAD

**Issue by TeaRex-coder** [Prem-ium/BingRewards#70]
Using the prebuilt image from Docker Hub, starting the container with the latest tag for the image resulted in this error:

```
Exception: local variable 'options' referenced before assignment

Traceback (most recent call last):
  File "/app/main.py", line 1395, in main
    start_rewards()
  File "/app/main.py", line 1275, in start_rewards
    driver = get_driver()
  File "/app/main.py", line 258, in get_driver
    options.add_argument('--no-sandbox')
UnboundLocalError: local variable 'options' referenced before assignment



 Attempting to restart Bing Rewards Automation in 10 minutes...
```

I let it sit for 30 minutes and it didn't work.
I also tried building the image myself from this repo but no dice.

Server info:
- OS: Ubuntu Server 22.04.02
- CPU arch: X86

**Comment by vay1314** [comment]
Same Question, why is that？

**Comment by Lexxior** [comment]
I get this error too

**Comment by Prem-ium** [comment]
May be an issue with your BROWSER variable, make sure it is following the description.

**Comment by TeaRex-coder** [comment]
Thanks for the reply and suggestion. I'll have a look this weekend!

**Comment by HuiMi24** [comment]
the BROWSER should be chrome instead of 'chrome' in the .env file

**Comment by Lexxior** [comment]
> the BROWSER should be chrome instead of 'chrome' in the .env file

This does not work for me
also it says `# Not used in Docker` for browser in the .env

**Comment by Lexxior** [comment]
I just checked again, for me it's actually a different error code

`HANDLE_DRIVER: 
Starting Bing Rewards Bot...
   Traceback (most recent call last):
File "/app/main.py", line 30, in <module>
    if not os.environ["LOGIN"]:
  File "/usr/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOGIN'`
