### ISSUE TITLE
Error running docker image from README

### ISSUE THREAD

**Issue by mattsingh** [Prem-ium/BingRewards#92]
Running `main.py` locally works however

Here's the error message
```
$ docker run -it --env-file ./.env --restart unless-stopped --name bing-rewards nelsondane/bing-rewards:latest 
Unable to find image 'nelsondane/bing-rewards:latest' locally
latest: Pulling from nelsondane/bing-rewards
677076032cca: Pull complete 
70abf8e21a4e: Pull complete 
02393c4c8679: Pull complete 
0a0d40123cae: Pull complete 
fd688bf4a53e: Pull complete 
0a4d6751d8e3: Pull complete 
c659be54b473: Pull complete 
c2567d2a5ed9: Pull complete 
03fa7b0993ff: Pull complete 
ea1e57bc5154: Pull complete 
Digest: ----
Status: Downloaded newer image for nelsondane/bing-rewards:latest
rm: cannot remove '/tmp/.X99-lock': No such file or directory
Starting X virtual framebuffer (Xvfb) in background...
BROWSER: 'chrome'
HANDLE_DRIVER: True
Starting Bing Rewards Bot...
Current IPv4 Address: -----
Unable to get IPv6 address


Starting Bing Rewards Automation:	2023-05-12 14:50:39.385435-04:00

Exception: local variable 'options' referenced before assignment

Traceback (most recent call last):
  File "/app/main.py", line 1395, in main
    start_rewards()
  File "/app/main.py", line 1275, in start_rewards
    driver = get_driver()
  File "/app/main.py", line 258, in get_driver
    options.add_argument('--no-sandbox')
UnboundLocalError: local variable 'options' referenced before assignment
```

**Comment by Prem-ium** [comment]
That version is now outdated and unmaintained as the developer has chosen to discontinue it. You can follow the new instructions to build it.

**Comment by Taoshan98** [comment]
Same error here.

To Fix edit these parameters in .env file:
Set BROWSER value without quotes like this -> chrome (not 'chrome')
Set TZ value without quotes like this -> Europe/Rome (not 'Europe/Rome')
Change CURRENCY property name to CUR_SYMBOL
